name: Perceptia
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Test on all platforms
    runs-on: ${{ matrix.os }}  # Use the OS from the matrix

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      # Step 3: Install system dependencies (Linux only)
      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev mesa-utils

      # Step 4: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the app (with software rendering on Linux)
      - name: Run the app
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # Use software rendering on Linux
            LIBGL_ALWAYS_SOFTWARE=1 python main.py
          else
            # Skip graphical tests on Windows and macOS
            echo "Skipping graphical tests on ${{ matrix.os }}."
          fi
