name: Perceptia
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgl1-mesa-glx libglfw3 libglfw3-dev mesa-utils
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          echo "Virtual display started on DISPLAY=:99"
      
      - name: Install OpenGL Dependencies on Windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          choco install -y opengl mesa glfw
          $env:LIBGL_ALWAYS_INDIRECT = "1"
          [Environment]::SetEnvironmentVariable("LIBGL_ALWAYS_INDIRECT", "1", "Machine")
          Write-Output "LIBGL_ALWAYS_INDIRECT set to 1"

      - name: Install OpenGL Dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install glfw
          brew install mesa

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade --force-reinstall pip
          pip install -r requirements.txt

      - name: Run Python OpenGL Application
        env:
          DISPLAY: ":99"  # Only relevant for Linux
        run: |
          python main.py  # Replace with your actual script
